---
  # Annex A1 - Singularity Installation
  - name: Annex A1 - Download Go v{{ GOLANG.VERSION }}
    get_url:
      url: "https://storage.googleapis.com/golang/go{{ GOLANG.VERSION }}.linux-amd64.tar.gz"
      dest: /tmp
      checksum: "sha256:{{ GOLANG.SHA256_CHECKSUM }}"
      mode: 0440

  - name: Annex A1 - Extract Go archive into {{ GOLANG.DIR }}
    unarchive:
      src: "/tmp/go{{ GOLANG.VERSION }}.linux-amd64.tar.gz"
      dest: "{{ GOLANG.DIR }}"
      copy: no

  - name: Annex A1 - Create Go Binary Symbolic Link from {{ GOLANG.DIR }} to /usr/bin
    file:
      src: "{{ GOLANG.DIR }}/go/bin/go"
      dest: /usr/bin/go
      owner: root
      group: root
      state: link

  - set_fact:
      expected_singularity_version: "{{ SINGULARITY_VERSION }}" 

  - name: Annex A1.1 - Check Singularity existence
    stat:
      path: /usr/bin/singularity
    register: singularity
  
  - name: Annex A1.1 - Check Singularity version if exists
    shell: "{{ singularity.stat.path }} version"
    when: singularity.stat.exists
    register: singularity_version

  - name: Annex A1.1 - Git clone Singularity Repository and checkout v{{ SINGULARITY_VERSION }}
    git:
      repo:  https://github.com/hpcng/singularity.git
      dest: /usr/local/singularity
      clone: yes
      version: "v{{ SINGULARITY_VERSION }}"

  - name: Annex A1.1 - Configure Singularity v{{ SINGULARITY_VERSION }} from source
    shell:
      cmd: ./mconfig 
      chdir: /usr/local/singularity
    when: singularity.stat.exists == False or singularity_version.stdout.find(expected_singularity_version) == -1
  
  - name: Annex A1.1 - Build Singularity v{{ SINGULARITY_VERSION }} from source
    shell:
      cmd: make -C ./builddir 
      chdir: /usr/local/singularity
    when: singularity.stat.exists == False or singularity_version.stdout.find(expected_singularity_version) == -1
     
  - name: Annex A1.1 - Install Singularity v{{ SINGULARITY_VERSION }} from source
    shell:
      cmd: make -C ./builddir install 
      chdir: /usr/local/singularity
    when: singularity.stat.exists == False or singularity_version.stdout.find(expected_singularity_version) == -1

  - name: Annex A1 - Create Singularity Binary Symbolic Link from to /usr/bin
    file:
      src: /usr/local/bin/singularity
      dest: /usr/bin/singularity
      owner: root
      group: root
      state: link