---
  - name: Annex B - Tune Kernel Network Parameters
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      state: present
      reload: yes
    with_items:
      - { name: 'net.ipv4.tcp_congestion_control', value: 'htcp' }
      - { name: 'net.ipv4.tcp_mtu_probing', value: '1' }
      - { name: 'net.core.rmem_max', value: '2147483647' }
      - { name: 'net.core.wmem_max', value: '2147483647' }
      - { name: 'net.ipv4.tcp_rmem', value: '4096 87380 2147483647' }
      - { name: 'net.ipv4.tcp_wmem', value: '4096 65536 2147483647' }
      - { name: 'net.core.default_qdisc', value: 'fq' }
      - { name: 'net.ipv4.conf.default.rp_filter', value: '0' }
      - { name: 'net.ipv4.conf.all.rp_filter', value: '0' }
      - { name: 'net.ipv4.ip_forward', value: '0' }
      - { name: 'net.core.netdev_max_backlog', value: '250000' }
      - { name: 'net.ipv4.tcp_no_metrics_save', value: '1' }