---
  - name: Annex F2 - Download prerequisite to manager Docker via Ansible
    pip:
      name: docker-py==1.10.6
      state: present

  - name: "Annex F2 - Setup PerfSONAR Testpoint {{ PERFSONAR.VERSION }} Docker container"
    docker_container:
      name: perfsonar-testpoint
      image: "perfsonar/testpoint:{{ PERFSONAR.VERSION }}"
      state: started
      recreate: yes
      restart_policy: always
      network_mode: host
