---
  - name: Annex F2 - Download prerequisite to manager Docker via Ansible
    pip:
      name: docker-py==1.10.6
      state: present

  - name: "Annex F2 - Setup PerfSONAR Testpoint {{ PERFSONAR.VERSION }} Docker container"
    docker_container:
      name: perfsonar-testpoint
      image: "perfsonar/testpoint:{{ PERFSONAR.VERSION }}"
      state: absent
      recreate: yes
      restart_policy: always
      network_mode: host

  - name: Annex F2 - Download PerfSONAR Sources List
    get_url:
      url: http://downloads.perfsonar.net/debian/perfsonar-release.list
      dest: /etc/apt/sources.list.d/
  
  - name: Annex F2 - Add PerfSONAR Repository GPG Key
    apt_key:
      url: http://downloads.perfsonar.net/debian/perfsonar-official.gpg.key
      state: present
    
  - name: Annex F2 - Install perfsonar-testpoint
    apt: 
      name:
        - perfsonar-testpoint
        - perfsonar-toolkit-ntp
        - perfsonar-toolkit-servicewatcher
      state: latest
      update_cache: yes 
  
  - name: Annex F2 - Check existence of PerfSONAR lsregistrationdaemon Configuration
    stat:
      path: /etc/perfsonar/lsregistrationdaemon.conf
    register: lsregistrationdaemon

  - name: Annex F2 - Recover PerfSONAR lsregistrationdaemon Configuration
    copy:
      src: /etc/perfsonar/lsregistrationdaemon.conf.dpkg-bak
      dest: /etc/perfsonar/lsregistrationdaemon.conf
      owner: root
      group: root
      mode: 0644
    when: lsregistrationdaemon.stat.exists == False
    
  - name: Annex F2 - Enable and Restart PerfSONAR Services
    systemd:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - perfsonar-lsregistrationdaemon
      - pscheduler-archiver
      - pscheduler-runner
      - pscheduler-scheduler
      - pscheduler-ticker
      - psconfig-pscheduler-agent

  - name: Set PerfSONAR ping permissions
    file:
      path: /usr/bin/ping
      owner: root
      group: root
      mode: '4755'
