---
  - name: Annex F2 - Download PerfSONAR Sources List
    get_url:
      url: http://downloads.perfsonar.net/debian/perfsonar-release.list
      dest: /etc/apt/sources.list.d/
  
  - name: Annex F2 - Add PerfSONAR Repository GPG Key
    apt_key:
      url: http://downloads.perfsonar.net/debian/perfsonar-official.gpg.key
      state: present
    
  - name: Annex F2 - Install perfsonar-testpoint
    apt: 
      name:
        - perfsonar-testpoint
        - perfsonar-toolkit-ntp
        - perfsonar-toolkit-servicewatcher
      state: latest
      update_cache: yes 
    notify: Enable and Restart PerfSONAR Services
    
  - name: Annex F2 - Enable and Restart PgSQL Service for PerfSONAR
    systemd:
      name: postgresql
      state: restarted
      enabled: yes

  - name: Annex F2 - Load PerfSONAR Automated IPv4 Test Mesh
    shell:
      cmd: psconfig remote add --configure-archives https://203.30.39.11/psconfig/dmc-v4-maddash-dashboard.json
    register: psv4

  - debug: var=psv4.stdout_lines

  - name: Annex F2 - Load PerfSONAR Automated IPv6 Test Mesh
    shell:
      cmd: psconfig remote add --configure-archives https://203.30.39.11/psconfig/dmc-v6-maddash-dashboard.json
    register: psv6

  - debug: var=psv6.stdout_lines
