---
  - name: Annex G - Install elbencho prerequisites
    apt:
      name:
        - build-essential
        - debhelper
        - devscripts
        - fakeroot
        - git
        - libaio-dev
        - libboost-filesystem-dev
        - libboost-program-options-dev
        - libboost-thread-dev
        - libncurses-dev
        - libnuma-dev
        - lintian
  
  - name: Annex G - Clone elbencho Git repository
    git:
      clone: yes
      repo: https://github.com/breuner/elbencho.git
      dest: "{{ ELBENCHO.DIR }}/elbencho"
      version: "v{{ ELBENCHO.VERSION }}"
      
  - name: Annex G - Make elbencho Debian Package
    shell:
        cmd: make deb
        chdir: "{{ ELBENCHO.DIR }}/elbencho"
  
  - name: Annex G - Install elbencho
    apt:
      deb: "{{ ELBENCHO.DIR }}/elbencho/packaging/elbencho_{{ ELBENCHO.PACKAGE }}_amd64.deb"
        
  
  
