---   
  - name: Update all packages
    yum:
      name: "*"
      state: latest
      update_cache: yes

  - name: Annex A1 - Install epel-release release
    yum:
      name: epel-release
      state: present

  - name: Annex A1 - Install iperf3
    yum:
      name:
        - iperf3
        - lshw
      state: present