---  
  - name: Annex A1 - Install CentOS Development Tools
    yum:
      name: "@Development tools"
      state: latest
  
  - name: Annex A1 - Retrieve Singularity pre-requisites including Golang
    yum:
      name:
        - openssl-devel
        - libuuid-devel
        - libseccomp-devel
        - wget
        - squashfs-tools
        - cryptsetup
      state: latest
