---
  - name: Annex A2 - Install required system packages for Docker CE
    yum: 
      name:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2        
      state: latest
       
  - name: Annex A2 - Add Docker CE Repository
    get_url:
     url: https://download.docker.com/linux/centos/docker-ce.repo
     dest: /etc/yum.repos.d/docker-ce.repo

  - name: Annex A2 - Install Docker
    yum: 
      name: docker 
      state: latest
    notify: Enable and Restart Docker

  - name: Annex A2 - Install docker-compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.29.1/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'