---
  - name: Annex F1 - Permit Node_Exporter traffic on Port 9100/TCP in Firewalld
    firewalld:
      port: 9100/tcp
      permanent: yes
      state: enabled
      immediate: true
      zone: public

  - name: Annex F2 - Enable PerfSONAR RPM Repository
    yum:
      name:  http://software.internet2.edu/rpms/el7/x86_64/latest/packages/perfSONAR-repo-0.10-1.noarch.rpm
      state: latest

  - name: Annex F2 - Install perfsonar-testpoint & PerfSONAR NTP and PerfSONAR ServiceWatcher bundles 
    yum : 
      name:
        - perfsonar-testpoint
        - perfsonar-toolkit-ntp
        - perfsonar-toolkit-servicewatcher
        - perfsonar-toolkit-security
      state: latest
    notify: Enable and Restart PerfSONAR Services

  - name: Annex F2 - Enable and Restart PgSQL Service for PerfSONAR
    systemd:
      name: postgresql-10
      state: restarted
      enabled: yes