---
  - name: Annex G - Install centos-release-scl for elbencho
    yum:
      name: centos-release-scl
      state: present
        
  - name: Annex G - Install elbencho prerequisites
    yum:
      name:
        - boost-devel
        - gcc-c++
        - git
        - libaio-devel
        - make
        - ncurses-devel
        - numactl-devel
        - rpm-build
        - devtoolset-8
      state: present
       
  - name: Annex G - Clone elbencho Git repository
    git:
      clone: yes
      repo: https://github.com/breuner/elbencho.git
      dest: "{{ ELBENCHO.DIR }}/elbencho"
      version: "v{{ ELBENCHO.VERSION }}-1"
      
  - name: Annex G - Make elbencho RPM Package
    shell: "source /opt/rh/devtoolset-8/enable && make rpm" 
    args:  
      chdir: "{{ ELBENCHO.DIR }}/elbencho"
      executable: /bin/bash
            
  
  - name: Annex G - Install elbencho RPM
    yum:
      name: "{{ ELBENCHO.DIR }}/elbencho/packaging/RPMS/x86_64/elbencho-{{ ELBENCHO.VERSION }}.0-1.x86_64.rpm"
        
  
  
