---
  - name: Annex H - Add trusted DMC IPs to firewall to allow incoming traffic
    firewalld:
      zone: trusted
      permanent: yes
      immediate: yes
      source: "{{ item.IP }}"
      state: enabled
    with_items:
      - "{{ TRUSTED_HOSTS.IPV4 }}"
      - "{{ TRUSTED_HOSTS.IPV6 }}"